repository: flnav/flnav.github.io
repository_url: https://github.com/flnav/flnav.github.io

timezone: Asia/Shanghai
lang: zh_CN
title: 飛龍在线 · FeiLong-Online
alias_en: FL-Online
alias_cn: 飛龍在线
description: FeiLong-Online
keywords: 飛龍, search, FL, Nav, Navigation, Online
url: https://flpro.cn/
established_at: "2022-07-20T00:00+08:00"

author: ShiFeilong
author_url: https://flpro.cn/
organization: 鲁ICP备2024111425号
organization_url: https://beian.miit.gov.cn/
contact: contact[at]flpro[dot]cn

image: /images/logo.png
logo: /images/logo.png
logo_dark: /images/logo-dark.svg
logo_white: /images/logo-white.svg

update_interval: 60000

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - .gitignore
  - .travis.yml
  - LICENSE
  - README.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - script
  - vendor
  - app.py            # 排除 app.py 文件
  - templates/        # 排除 templates 文件夹
  - log.dat           # 排除 log.dat 文件
  - out.dat           # 排除 out.dat 文件
  - users.db          # 排除 users.db 文件
