repository: flnav/flnav.github.io
repository_url: https://github.com/flnav/flnav.github.io

timezone: Asia/Shanghai
lang: zh_CN

title: 飛龍导航 · FL-Nav
alias_en: FL-Nav
alias_cn: 飛龍导航
description: 飛龍Navigation 
keywords: 飛龍, search, FL, Nav, Navigation
url: https://flpro.cn
established_at: "2022-07-20T00:00+08:00"

author: Feilong
author_url: https://flpro.cn
organization: 鲁ICP备2021034838号-2
organization_url: https://wap.miit.gov.cn
contact: contact[at]flpro[dot]cn

image: /images/logo.png
logo: /images/logo.png
logo_dark: /images/logo-dark.svg
logo_white: /images/logo-white.svg

update_interval: 60000

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor